version: '3.5'

services:
  application:
    container_name: seat
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=seat
    ports:
      - '1000:8000'
    networks:
      - seat-network

networks:
  seat-network:
